spring:
  datasource:
    url: jdbc:mysql://localhost:3306/random_cat?createDatabaseIfNotExist=true
    username: root
    password: docker
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: random-cat

development:
  templateResolverCacheable: false

aws:
#  enabled: true
  region: eu-central-1
  bucketName: ddd-cat-bucket

randomCat:
  historySize: 20

scheduled:
  reset: "0 0 0 * * *"
